### ISSUE TITLE
vuepress网页提交

### ISSUE THREAD

**Issue by qigedandan** [JinweiOS/lets-web-1#33]
## myblog
> https://qigedandan.github.io/vuepress-blog/
## 收获
> 学习了git的更多使用技巧
> 搭建了博客
> 学习github action的使用
## 疑问
> vuepress博客通过直接clone,并不理解vue的使用方法
> git action比较复杂,没有学会怎么编写
> 没有学到如何新建博客文章

**Comment by JinweiOS** [comment]
我解答下疑问哈~

+ 今天的核心在于理解什么是DevOps，如何去做CI/CD，通过搭建vuepress博客，去理解基于框架的代码如何做CI&CD。gh-action是CI/CD的一种实践方式，例如国内的码云也有自己的DevOps方案。![image](https://user-images.githubusercontent.com/105687126/170825426-9aaf9135-3387-4281-8fe1-184a089e496b.png)

+ gh-action功能还是挺多的，编写的描述文件是yml格式，需要对数组，对象等概念有理解。概念涉及广泛，因此简化后目标是知道有github action，并且知道是用来做什么的

+ 新建博客明天补一下哈哈哈哈~

💪加油，一起进步~
