### ISSUE TITLE
zhou's opinion

### ISSUE THREAD

**Issue by hcnzhou** [JinweiOS/lets-web-1#34]
- Start Date: 2022-05-28

# Github ID
hcnzhou

# Links
Give us your first or not first markdown doc

For example:
This is my first rfc: [useevent](https://github.com/reactjs/rfcs/blob/useevent/text/0000-useevent.md)

# Advice

彭老师YYDS，希望讲知识点的时候能够把为什么要这么干讲的细致一些，这样能更好的理解操作背后的意义和操作的用处

# Wish

希望学的越来越好，英格越来越好

# Q&A

give Mr.peng＋＄

**Comment by JinweiOS** [comment]
哈哈哈哈，可能我讲得比较快，我理解一开始我们需要关注怎么操作，这个操作能产生什么影响。先屏蔽细节原理，可以理解遵循广度优先，然后再到深度~💪加油
