### ISSUE TITLE
what do you want to express?

### ISSUE THREAD

**Issue by bbj1030** [JinweiOS/lets-web-1#4]
- Start Date: 2022-05-20

# Github ID
@bbj1030

# Advice
彭老师特别好，我感觉我入门了，希望可以保持交流。

# Wish

我期望我能够写一个微信小程序，并且用户量过万

# Q&A
怎么报名呀？我现在基础比较差能不能学得会呀？因为我是转专业的，所以我没有信心，我能学好吗？感谢老师能够回复我的问题！

**Comment by JinweiOS** [comment]
小程序可以，希望到时候我能成为你的contributor~~
正式课的设计也是从0基础开始的哈~整体上大概分为这么[几个阶段](https://docs.qq.com/doc/DT3RwU2NET01vdXNo?u=c501ea3219be418987213f34e5e7173a)，课程我还在设计中...
